productividad/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio,name="inicio"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
]

productos/urls.py
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path("",views.index, name="index"),
    path("formulario",views.formulario, name="formulario"),
    path("<int:producto_id>",views.detalle,name='detalle')
]

productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=30)
    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre = models.CharField(max_length=30)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

productos/forms.py
from . import models
from django.forms import ModelForm

class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre','stock','puntaje','categoria']

productividad/views.py
from django.shortcuts import render

def inicio(request):
    return render(
        request,
        "inicio.html",
    )

productos/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .forms import ProductoForm
from .models import Producto
# Create your views here.

def index(request):
    productos=Producto.objects.all()
    return render(
        request,
        'index.html',
        context={'productos':productos}
    )

def detalle(request,producto_id):
    producto = Producto.objects.get(id=producto_id)

    return render(
        request,
        'detalle.html',
        context={'producto':producto}
    )

def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/productos")
        
    form = ProductoForm()
    return render(
        request,
        "producto_form.html",
        {'form':form}
    )

productos/templates/detalle.html
{% extends "base.html" %}


{% block content %}

<div class="contenedor">
    <h6>{{producto.nombre}} </h6>
    <p>{{producto.stock}}</p>
    <p>{{producto.puntaje}}</p>
    <p>{{producto.categoria}}</p>
</div>

{% endblock %}

productos/templates/index.html
{% extends 'base.html'%}

{% block content %}

<h1>Productos</h1>

<a href="{% url 'productos:formulario' %}">agregar nuevo producto</a>

<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoria</th>
        </tr>
    </thead>
    
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id%}">
                    {{producto.nombre}}
                </a>
            </td>
            <td>{{producto.stock}}</td>
            <td>{{producto.puntaje}}</td>
            <td>{{producto.categoria}}</td>
        </tr>
        {% endfor%}
    </tbody>
</table>

{% endblock %}

productos/templates/producto_form.html
{% extends "base.html" %}

{%block content%}
<form action="{%url 'productos:formulario'%}" method='post'>

    {% csrf_token %}
    {{form}}

    <input class="btn btn-primary" type="submit" value="enviar">
</form>

{%endblock%}